# hugo.toml
baseURL = "https://cabear.com/"
canonifyURLs = true
languageCode = "en-us"
title = "BEAR RV, Truck, Auto Body Collision Repair & Paint"   # <-- was "My New Hugo Site"
enableRobotsTXT = false

# Optional: if you don't want tag & taxonomy listing pages indexed/created
# disableKinds = ["taxonomy", "term"]

[params]
brand_name = "BEAR RV, Truck, Auto Body Collision Repair & Paint"
brand_short = "BEAR"
home_seo_title = "RV & Truck Collision & Paint | Hayward & San Francisco Bay Area | BEAR"
description = "RV, truck, trailer, and auto body collision repair in Hayward, CA and the San Francisco Bay Area. Since 1979. PPG paint, frame, welding, insurance support."

theme = "hugo-arcana"

[taxonomies]
# no categories or tags


[menu]

  # Welcome
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  # RV
  [[menu.main]]
  identifier = "rv"
  name = "RV & Motorhome Repair"
  url = "/rv-repair/"
  weight = 2

    [[menu.main]]
    parent = "rv"
    name = "RV Upgrades"
    url = "/rv-repair/rv-upgrades/"
    weight = 1

    [[menu.main]]
    parent = "rv"
    name = "RV Maintenance"
    url = "/rv-repair/rv-maintenance/"
    weight = 2

    [[menu.main]]
    parent = "rv"
    name = "RV Collision Repair"
    url = "/rv-repair/rv-collision-repair/"
    weight = 3

    [[menu.main]]
    parent = "rv"
    name = "Motorhome Collision Repair"
    url = "/rv-repair/motorhome-collision-repair/"
    weight = 4

    [[menu.main]]
    parent = "rv"
    name = "RV Painting"
    url = "/rv-repair/rv-painting/"
    weight = 5


  # Commercial Truck
  [[menu.main]]
  identifier = "commercial-truck-repair"
  name = "Commercial Truck Repair"
  url = "/commercial-truck-repair/"
  weight = 3

    [[menu.main]]
    parent = "commercial-truck-repair"
    name = "Truck Collision Repair"
    url = "/commercial-truck-repair/truck-collision-repair/"
    weight = 1

    [[menu.main]]
    parent = "commercial-truck-repair"
    name = "Utility Truck Body Repair"
    url = "/commercial-truck-repair/utility-truck-body-repair/"
    weight = 2

    [[menu.main]]
    parent = "commercial-truck-repair"
    name = "Utility Truck Body Refinishing"
    url = "/commercial-truck-repair/utility-truck-body-refinishing/"
    weight = 3

#    [[menu.main]]
#    parent = "commercial-truck-repair"
#    identifier = "trailer-repair"
#    name = "Trailer Repair"
#    url = "/commercial-truck-repair/trailer-repair/"
#    weight = 4

#    [[menu.main]]
#    parent = "commercial-truck-repair"
#    name = "Lift Gate Installation"
#    url = "/commercial-truck-repair/trailer-repair/lift-gate-installation/"
#    weight = 5


  # Vehicles
  [[menu.main]]
  identifier = "vehicles"
  name = "Vehicles"
  url = "/auto-body-repair-shop/"
  weight = 5

    [[menu.main]]
    parent = "vehicles"
    name = "Frame Repair"
    url = "/auto-body-repair-shop/frame-repair/"
    weight = 1

    [[menu.main]]
    parent = "vehicles"
    name = "Restoration"
    url = "/auto-body-repair-shop/restoration/"
    weight = 2


  [[menu.main]]
  identifier = "metal-restoration"
  name = "Metal Restoration"
  url = "/metal-restoration/"
  weight = 6

    [[menu.main]]
    parent = "metal-restoration"
    name = "Abrasive Blasting"
    url = "/metal-restoration/abrasive-blasting/"
    weight = 1

    [[menu.main]]
    parent = "metal-restoration"
    name = "Fabrication & Repair"
    url = "/metal-restoration/fabrication-repair/"
    weight = 2



# Insurance
[[menu.main]]
identifier = "insurance"
name = "Insurance"
url = "/insurance/"
weight = 7

  [[menu.main]]
  parent = "insurance"
  name = "Direct Repair Program"
  url = "/insurance/direct-repair-program/"
  weight = 1


  # About
  [[menu.main]]
  name = "About Us"
  url = "/about-us/"
  weight = 8

  # Contact
  [[menu.main]]
  name = "Contact Us"
  url = "/contact-us/"
  weight = 9

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
