baseURL = "http://localhost:1313/"
# baseURL = "https://cabear.com/hugo/"
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hugo-arcana"
# theme = "ananke"

[menu]
  [[menu.main]]
  name = "Welcome"
  url = "/home/"
  weight = 1

  [[menu.main]]
  name = "RV Repair"
  url = "/rv-repair/"
  weight = 2

  [[menu.main]]
  identifier = "truck-services"
  name = "Truck Repair"
  url = "/truck-services/"
  weight = 3

  [[menu.main]]
  identifier = "sandblasting"
  name = "Sandblasting"
  url = "/media-sandblasting/"
  weight = 5

  [[menu.main]]
  identifier = "insurance"
  name = "Insurance"
  url = "/insurance-partnership/"
  weight = 5


  [[menu.main]]
  identifier = "about"
  name = "About Us"
  url = "/about-us/"
  weight = 5


  [[menu.main]]
  identifier = "welding"
  name = "Welding"
  url = "/welding/"
  weight = 6

  [[menu.main]]
  identifier = "frame-repair"
  name = "Frame Repair"
  url = "/frame-repair/"
  weight = 7

  [[menu.main]]
  identifier = "painting"
  name = "Painting"
  url = "/painting/"
  weight = 8

  [[menu.main]]
  identifier = "vehicle-decals"
  name = "Vehicle Decals"
  url = "/vehicle-decals/"
  weight = 9

  [[menu.main]]
  identifier = "stencil-painting"
  name = "Stencil Painting"
  url = "/stencil-painting/"
  weight = 10

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 11


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
