name: Deploy to Bluehost via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.134.1'
          extended: true

      - name: Build site
        run: hugo --baseURL "https://cabear.com/hugo/"

      - name: Deploy to Bluehost via SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan cabear.com >> ~/.ssh/known_hosts
          rsync -avz --delete public/ eogoaomy@cabear.com:~/public_html/hugo/
